services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "6052:6052"
      - "6053:6053"
    depends_on:
      - esphome
    restart: always
    networks:
      - esphome_network

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    expose:
      - "6052"
    ports:
      - "6055:6052"
    environment:
      - USERNAME=daanyaal
      - PASSWORD=1505
      - PORT=6052
      - HOST=0.0.0.0
    networks:
      - esphome_network

networks:
  esphome_network:
    driver: bridge